### ISSUE TITLE
Not showing in Integrations

### ISSUE THREAD

**Issue by ryanbrown783** [amaximus/anniversary#1]
After install from HACS and restart of hassio, it is not visible in the integrations tab.

**Comment by jonwaland** [comment]
You need to add the config via YAML, as a new sensor - I dont think there is a guided way via the GUI

**Comment by ryanbrown783** [comment]
I did that but I get an error saying there is no integration. I watched a video on the steps and for some reason after installing it from HACS it won’t show in my integration tab.  Looking at the files it looks like everting installed fine, except the init.py is blank.

**Comment by amaximus** [comment]
Once you install it from HACS, configure it and restart HA, the integration will appear under HACS Integrations.

This integration does not support configuration flow, so you'll have to configure it via yaml file.

Please double check it under HACS integrations and get back to me with results.

**Comment by ryanbrown783** [comment]
So I went through all the documentation.  I followed everything, but this part is not an option "Anniversaries can be configured on the integrations menu or in configuration.yaml"

When I go into my config file and add the config example: 
"# Example configuration.yaml entry

anniversaries:
  sensors:
  - name: Shakespeare's Birthday
    date: '1564-04-23'
  - name: Shakespeare's Wedding Anniversary
    date: '1582-11-27'"

I receive the following error:
Component error: anniversaries - Integration 'anniversaries' not found.

**Comment by ryanbrown783** [comment]
I just looked through all the files in the repo and the files are not all present in the custom comments and one of the files is completely blank.  I tried to install it twice from HACS with the same result.

**Comment by robertolamm** [comment]
Hello, I am new of all the HA,
I edited my configuration.yaml introducing the example:

platform: anniversary
name: events
multiple: true
anniversaries:
  - event: 'Doug birthday'
    date: '2000-1-15'
  - event: 'Steve Butabi'
    date: '2000-09-15'
    icon: mdi:cake-variant
  - event: 'Chazz birthday'
    date: '9-15'
    icon: mdi:cake-variant
  - event: 'Frank the tank'
    date: '1998-8-18'

Unfortunately in the configuration verify I got an error: integration not present.

But the integration in the HACS section is loaded and apparently ok.

I previous installed the anniversaries integration but I would like to use the yours.

Where I am wrong?

Thank you so much.

**Comment by jonwaland** [comment]
@ryanbrown783  your yaml is wrong - it is a custom sensor platform, not a new "integration".

If you have a seperate sensor.yaml try this:

```
- platform: anniversary
  name: events
  multiple: true
  anniversaries:
    - event: "A birthday"
      date: '1999-01-20'
      icon: mdi:cake-variant
```

If you dont, try this in configuration.yaml - @robertolamm  - this is your example:
```
sensor:
  - platform: anniversary
    name: events
    multiple: true
    anniversaries:
      - event: "A birthday"
        date: '1999-01-20'
        icon: mdi:cake-variant
```
        
Note the default format of Date is YYY-MM-DD
