### ISSUE TITLE
event type

### ISSUE THREAD

**Issue by Jase53** [amaximus/anniversary#11]
Hi. Is it possible to do below? I want to add type for the anniversary so when i have my button card i can use entity_picture and change the picture based on if state is equal to birthday or new year for example. 
  sensor:
    platform: anniversary
    name: events
    multiple: true
    anniversaries:
      - event: 'Jasons birthday'
        date: '1987-06-22'
        type: birthday
      - event: 'Johannas birthday'
        date: '1991-10-18'
        type: birthday
      - event: 'new year'
        date: '12-31'
        type: 'new year'

**Comment by amaximus** [comment]
Hi, yes, the integration supports event types in the list of anniversaries. You'll have to set items parameter to a non-zero value. This way the upcoming <items> events will be listed in the attributes.
The UI part (button card, entity_picture) is out of scope of this integration, but it can be achieved what you described.

**Comment by Jase53** [comment]
Hi. I do not fully understand what i have to change? can you ellaborate please.

Regarding UI part i will use custom button card.

**Comment by amaximus** [comment]
You should add e.g. 'items: 2' after 'multiple: true' then restart HA. This will list the next 2 upcoming events in the attributes in form of:
```
events: 
- event: 'Johannas birthday'
  event_in: '17'
  event_on: '2021-10-18'
  anniversary: '34'
  type: birthday
  icon: mdi:calendar
- event: 'new year'
  event_in: '91'
  event_on: '2021-12-31'
  type: new year
  icon: mdi:calendar
```
Then you can process the events attribute to display the information on the UI.
