### ISSUE TITLE
The sensor shows nothing

### ISSUE THREAD

**Issue by radaoggy** [amaximus/anniversary#18]
Is this add-on still in development? The sensor shows nothing. I have HA version 2022.10 with example code. State and attributes are empty.

```
sensor:
  - platform: anniversary
    name: events
    multiple: true
    anniversaries:
      - event: 'Doug birthday'
        date: '2000-1-15'
      - event: 'Steve Butabi'
        date: '2000-09-15'
        icon: mdi:cake-variant
      - event: 'Chazz birthday'
        date: '9-15'
        icon: mdi:cake-variant
      - event: 'Frank the tank'
        date: '1998-8-18'
```
