### ISSUE TITLE
trying to reuse example of button card

### ISSUE THREAD

**Issue by avico78** [amaximus/anniversary#19]
Thanks for this integration ,
I'd like to add the example button card to my ui ,
i actually copy paste it as is:
```
type: custom:button-card
size: 30px
styles:
  label:
    - font-size: 90%
  card:
    - height: 80px
  icon:
    - color: var(--paper-item-icon-color)
  grid:
    - position: relative
  custom_fields:
    notification:
      - background-color: >
          [[[
            if (states['sensor.events'].state > 1)
              return "var(--light-primary-color)";
            return "var(--accent-color)";
          ]]]
      - border-radius: 50%
      - position: absolute
      - left: 62%
      - top: 10%
      - height: 20px
      - width: 20px
      - font-size: 9px
      - line-height: 20px
custom_fields:
  notification: >
    [[[ return states['sensor.events'].state ]]]
label: >
  [[[
    var label = states['sensor.events'].attributes.first_event_name
    return label.replace("|","<br>");
  ]]]
color_type: icon
show_label: true
show_name: false
entity: sensor.events
```

getting error:

```
ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'attributes') in 'var label = states['sensor.events'].attributes.first_event_name return label.replace("|","<br>")...'
tap_action:
  action: more-info
type: custom:button-card
....
```
