### ISSUE TITLE
Not working with Home Assistant Core 2023.06.0

### ISSUE THREAD

**Issue by mikycol** [amaximus/anniversary#21]
After the update it stopped working giving the following error:
```
ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'attributes') in 'var label = states['sensor.events'].attributes.first_event_name return label.replace("|","<br>")...'
tap_action:
  action: more-info
type: custom:button-card
group_expand: false
hold_action:
  action: none
double_tap_action:
  action: none
layout: vertical
size: 30px
color_type: icon
show_name: false
show_state: false
show_icon: true
show_units: true
show_label: true
show_entity_picture: false
show_live_stream: false
card_size: 3
styles:
  label:
    - font-size: 90%
  card:
    - height: 80px
  icon:
    - color: var(--paper-item-icon-color)
  grid:
    - position: relative
  custom_fields:
    notification:
      - background-color: |
          [[[
            if (states['sensor.events'].state > 1)
              return "var(--light-primary-color)";
            return "var(--accent-color)";
          ]]]
      - border-radius: 50%
      - position: absolute
      - left: 62%
      - top: 10%
      - height: 20px
      - width: 20px
      - font-size: 9px
      - line-height: 20px
custom_fields:
  notification: |
    [[[ return states['sensor.events'].state ]]]
label: |
  [[[
    var label = states['sensor.events'].attributes.first_event_name
    return label.replace("|","<br>");
  ]]]
entity: sensor.events
default_color: var(--primary-text-color)
color_off: var(--paper-item-icon-color)
color_on: var(--paper-item-icon-active-color)
lock:
  enabled: false
  duration: 5
  unlock: tap

```
