### ISSUE TITLE
Anniversary value miscalculated

### ISSUE THREAD

**Issue by jurgenhaas** [amaximus/anniversary#4]
I have events configured like this:

```
platform: anniversary
name: events
multiple: true
anniversaries:
  - event: 'Name'
    date: '1998-10-9'
```

The card properly shows up in the UI. When I open the card and also open attributes, it shows the details. The last line shows `Anniversary: 22` and I guess this is the number of years since the original event. Shouldn't that be 23 in my example?
